spring:
  application:
    name: ledger
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: ledger
    default-schema: ledger
    create-schemas: true
dev.minkin.ledger:
  poller:
    batch-size: 500
  reconciler:
    fixed-delay-ms: 60000
    initial-delay-ms: 10000
  nats:
    url: nats://localhost:4222
    stream-name: LEDGER_EVENT_STREAM
    subjects: ledger.>
    entry-shard-count: 16
    stream-max-age: 10d
    consumer:
      entry:
        subject: ledger.entry.>
        consumer-name: entry-consumer
        max-deliver: 5
        ack-wait: 5s
    publisher:
      outbox:
        batch-size: 500


logging:
  level:
    root: info
    dev.minkin: debug